import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  pt: {
    // Common
    home: "Início",
    about: "Sobre",
    trust: "Confiança",
    terms: "Termos",
    checkout: "Checkout",
    contact: "Contacto",
    language: "Idioma",
    portuguese: "Português",
    english: "Inglês",
    spanish: "Espanhol",
    german: "Alemão",
    french: "Francês",
    ctaTitle: "Desafia a tua mente. Desvenda o mistério.",
    ctaText: "Prepara-te para uma experiência imersiva que te levará aos limites da tua perceção. O Paradox Protocol espera por ti.",
    startChallenge: "Iniciar Desafio",
    // TermsPage
    termsTitle: "Termos e Condições",
    termsIntro: "Bem-vindo ao Paradox Protocol. Ao aceder e utilizar os nossos serviços, concorda em cumprir os seguintes termos e condições. Por favor, leia-os atentamente.",
    acceptanceTitle: "1. Aceitação dos Termos",
    acceptanceText: "Ao utilizar o Paradox Protocol, o utilizador concorda com estes Termos e Condições, bem como com a nossa Política de Privacidade. Se não concordar com qualquer parte destes termos, não deverá utilizar os nossos serviços.",
    servicesTitle: "2. Descrição dos Serviços",
    servicesText: "O Paradox Protocol oferece uma plataforma de desafios de enigma e experiências interativas. Os nossos serviços podem incluir acesso a jogos, eventos e conteúdos digitais.",
    userAccountTitle: "3. Contas de Utilizador",
    userAccountText: "Para aceder a certas funcionalidades, poderá ser necessário criar uma conta. O utilizador é responsável por manter a confidencialidade das suas informações de conta e por todas as atividades que ocorram sob a sua conta.",
    paymentsTitle: "4. Pagamentos e Reembolsos",
    paymentsText: "Todos os pagamentos são processados de forma segura. As políticas de reembolso variam de acordo com o tipo de serviço ou produto adquirido e serão claramente indicadas no momento da compra.",
    intellectualPropertyTitle: "5. Propriedade Intelectual",
    intellectualPropertyText: "Todo o conteúdo e materiais disponíveis no Paradox Protocol, incluindo textos, gráficos, logótipos, imagens e software, são propriedade da Paradox Protocol ou dos seus licenciadores e estão protegidos por leis de propriedade intelectual.",
    prohibitedConductTitle: "6. Conduta Proibida",
    prohibitedConductText: "É proibido utilizar os nossos serviços para qualquer finalidade ilegal ou não autorizada. Isto inclui, mas não se limita a, violação de direitos de propriedade intelectual, envio de spam, ou distribuição de malware.",
    disclaimerTitle: "7. Isenção de Garantias",
    disclaimerText: "Os nossos serviços são fornecidos 'como estão', sem garantias de qualquer tipo, expressas ou implícitas. Não garantimos que os serviços serão ininterruptos, livres de erros ou seguros.",
    limitationOfLiabilityTitle: "8. Limitação de Responsabilidade",
    limitationOfLiabilityText: "Em nenhuma circunstância a Paradox Protocol será responsável por quaisquer danos diretos, indiretos, incidentais, especiais ou consequenciais resultantes do uso ou da incapacidade de usar os nossos serviços.",
    lawTitle: "9. Lei Aplicável e Jurisdição",
    lawText: "Estes Termos e Condições serão regidos e interpretados de acordo com as leis de Portugal. Qualquer disputa será submetida à jurisdição exclusiva dos tribunais de Lisboa.",
    prizeTitle: "10. Condições de Atribuição do Prémio",
    prizeText: "O valor total do prémio monetário de uma temporada ou desafio poderá estar condicionado à venda de um número mínimo de bilhetes. Caso esse mínimo não seja atingido, a Paradox Protocol reserva-se o direito de ajustar o valor do prémio proporcionalmente ou cancelar o desafio.",
    // CheckoutPage
    checkoutTitle: "Finalizar Compra",
    yourOrder: "O Seu Pedido",
    product: "Produto",
    quantity: "Quantidade",
    price: "Preço",
    total: "Total",
    shippingInformation: "Informações de Envio",
    fullName: "Nome Completo",
    address: "Morada",
    city: "Cidade",
    postalCode: "Código Postal",
    country: "País",
    paymentInformation: "Informações de Pagamento",
    cardNumber: "Número do Cartão",
    expirationDate: "Data de Validade",
    cvv: "CVV",
    placeOrder: "Finalizar Pedido",
    // TrustPage
    trustTitle: "A Nossa Confiança e Segurança",
    trustIntro: "No Paradox Protocol, a sua segurança e confiança são a nossa prioridade máxima. Estamos empenhados em fornecer um ambiente seguro e transparente para todos os nossos utilizadores.",
    dataSecurityTitle: "Segurança dos Dados",
    dataSecurityText: "Utilizamos tecnologias de encriptação avançadas para proteger os seus dados pessoais e financeiros. Todas as transações são processadas através de gateways de pagamento seguros.",
    privacyPolicyTitle: "Política de Privacidade",
    privacyPolicyText: "A sua privacidade é importante para nós. A nossa Política de Privacidade detalha como recolhemos, usamos e protegemos as suas informações. Não partilhamos os seus dados com terceiros sem o seu consentimento.",
    fairPlayTitle: "Jogo Justo e Transparência",
    fairPlayText: "Garantimos um jogo justo em todos os nossos desafios. Os nossos algoritmos são auditados regularmente para assegurar a integridade e a aleatoriedade dos resultados. A transparência é um pilar fundamental da nossa operação.",
    customerSupportTitle: "Apoio ao Cliente",
    customerSupportText: "A nossa equipa de apoio ao cliente está disponível 24/7 para responder a quaisquer questões ou preocupações que possa ter. A sua satisfação é a nossa prioridade.",
    validationProcessTitle: "Processo de Validação",
    validationProcessText: "Todos os desafios e resultados são submetidos a um rigoroso processo de validação para garantir a sua precisão e justiça. A nossa equipa de especialistas verifica cada etapa para assegurar a integridade da experiência.",
    // AboutPage
    aboutTitle: "Sobre Nós",
    aboutIntro: "O Paradox Protocol é uma equipa apaixonada por criar experiências de enigma imersivas e desafiadoras. Acreditamos que a mente humana é capaz de desvendar os mistérios mais complexos.",
    ourMissionTitle: "A Nossa Missão",
    ourMissionText: "A nossa missão é proporcionar desafios únicos que estimulem o pensamento crítico, a criatividade e a resolução de problemas. Queremos que cada utilizador se sinta um verdadeiro detetive.",
    ourVisionTitle: "A Nossa Visão",
    ourVisionText: "Ser a plataforma líder em experiências de enigma interativas, reconhecida pela inovação, segurança e pela comunidade de entusiastas que construímos.",
    ourTeamTitle: "A Nossa Equipa",
    ourTeamText: "Somos uma equipa multidisciplinar de designers de jogos, programadores, escritores e especialistas em segurança, todos unidos pela paixão por enigmas e mistérios.",
    // ContactPage
    contactTitle: "Contacte-nos",
    contactIntro: "Tem alguma questão, sugestão ou precisa de apoio? Estamos aqui para ajudar. Preencha o formulário abaixo ou utilize os nossos contactos diretos.",
    name: "Nome",
    email: "Email",
    message: "Mensagem",
    send: "Enviar",
    // HomePage
    heroTitle: "Desvenda o Mistério do Paradox Protocol",
    heroSubtitle: "Uma experiência de enigma imersiva que desafia a tua mente.",
    learnMore: "Saber Mais",
    featuredChallenges: "Desafios em Destaque",
    challenge1Title: "O Enigma da Cripta Esquecida",
    challenge1Desc: "Explora uma cripta antiga e desvenda os segredos de uma civilização perdida.",
    challenge2Title: "O Código do Hacker Fantasma",
    challenge2Desc: "Entra no mundo da cibersegurança e decifra o código de um hacker lendário.",
    challenge3Title: "O Labirinto dos Sonhos",
    challenge3Desc: "Navega por um labirinto surreal onde a realidade e a ilusão se misturam.",
    viewAllChallenges: "Ver Todos os Desafios",
    howItWorks: "Como Funciona",
    step1Title: "Escolhe o teu Desafio",
    step1Desc: "Seleciona entre uma variedade de enigmas e mistérios, cada um com a sua própria história e dificuldade.",
    step2Title: "Resolve os Enigmas",
    step2Desc: "Utiliza a tua lógica, criatividade e conhecimentos para desvendar pistas e resolver quebra-cabeças.",
    step3Title: "Desvenda o Mistério",
    step3Desc: "Conclui o desafio e descobre a verdade por trás do Paradox Protocol.",
    testimonials: "Testemunhos",
    testimonial1: "'Uma experiência incrível! Os enigmas são desafiadores e a história é cativante.' - Ana P.",
    testimonial2: "'Adorei cada minuto! Mal posso esperar pelo próximo desafio.' - João S.",
    testimonial3: "'O Paradox Protocol elevou os jogos de enigma a um novo nível.' - Sofia M.",
    faq: "Perguntas Frequentes",
    faq1Question: "O que é o Paradox Protocol?",
    faq1Answer: "O Paradox Protocol é uma plataforma de experiências de enigma interativas que desafiam a tua mente com mistérios e quebra-cabeças.",
    faq2Question: "Como posso participar?",
    faq2Answer: "Podes participar escolhendo um desafio, criando uma conta e seguindo as instruções para resolver os enigmas.",
    faq3Question: "Os desafios são para todas as idades?",
    faq3Answer: "Os nossos desafios são projetados para um público adulto, mas alguns podem ser adequados para adolescentes com supervisão.",
    faq4Question: "Posso jogar em equipa?",
    faq4Answer: "Sim, muitos dos nossos desafios podem ser jogados individualmente ou em equipa, proporcionando uma experiência colaborativa.",
    faq5Question: "Como posso contactar o apoio ao cliente?",
    faq5Answer: "Podes contactar o nosso apoio ao cliente através do formulário na página de Contacto ou por email.",
    footerText: "© 2025 Paradox Protocol. Todos os direitos reservados.",
  },
  en: {
    // Common
    home: "Home",
    about: "About",
    trust: "Trust",
    terms: "Terms",
    checkout: "Checkout",
    contact: "Contact",
    language: "Language",
    portuguese: "Portuguese",
    english: "English",
    spanish: "Spanish",
    german: "German",
    french: "French",
    ctaTitle: "Challenge your mind. Unravel the mystery.",
    ctaText: "Prepare for an immersive experience that will push the limits of your perception. The Paradox Protocol awaits you.",
    startChallenge: "Start Challenge",
    // TermsPage
    termsTitle: "Terms and Conditions",
    termsIntro: "Welcome to Paradox Protocol. By accessing and using our services, you agree to comply with the following terms and conditions. Please read them carefully.",
    acceptanceTitle: "1. Acceptance of Terms",
    acceptanceText: "By using Paradox Protocol, you agree to these Terms and Conditions, as well as our Privacy Policy. If you do not agree with any part of these terms, you should not use our services.",
    servicesTitle: "2. Description of Services",
    servicesText: "Paradox Protocol offers a platform for enigma challenges and interactive experiences. Our services may include access to games, events, and digital content.",
    userAccountTitle: "3. User Accounts",
    userAccountText: "To access certain features, you may need to create an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account.",
    paymentsTitle: "4. Payments and Refunds",
    paymentsText: "All payments are processed securely. Refund policies vary depending on the type of service or product purchased and will be clearly indicated at the time of purchase.",
    intellectualPropertyTitle: "5. Intellectual Property",
    intellectualPropertyText: "All content and materials available on Paradox Protocol, including text, graphics, logos, images, and software, are the property of Paradox Protocol or its licensors and are protected by intellectual property laws.",
    prohibitedConductTitle: "6. Prohibited Conduct",
    prohibitedConductText: "It is prohibited to use our services for any illegal or unauthorized purpose. This includes, but is not limited to, intellectual property infringement, spamming, or malware distribution.",
    disclaimerTitle: "7. Disclaimer of Warranties",
    disclaimerText: "Our services are provided 'as is', without warranties of any kind, express or implied. We do not guarantee that the services will be uninterrupted, error-free, or secure.",
    limitationOfLiabilityTitle: "8. Limitation of Liability",
    limitationOfLiabilityText: "In no event shall Paradox Protocol be liable for any direct, indirect, incidental, special, or consequential damages arising from the use or inability to use our services.",
    lawTitle: "9. Applicable Law and Jurisdiction",
    lawText: "These Terms and Conditions shall be governed by and construed in accordance with the laws of Portugal. Any dispute shall be submitted to the exclusive jurisdiction of the courts of Lisbon.",
    prizeTitle: "10. Prize Award Conditions",
    prizeText: "The total value of a season or challenge's monetary prize may be conditioned on the sale of a minimum number of tickets. If this minimum is not met, Paradox Protocol reserves the right to adjust the prize value proportionally or cancel the challenge.",
    // CheckoutPage
    checkoutTitle: "Checkout",
    yourOrder: "Your Order",
    product: "Product",
    quantity: "Quantity",
    price: "Price",
    total: "Total",
    shippingInformation: "Shipping Information",
    fullName: "Full Name",
    address: "Address",
    city: "City",
    postalCode: "Postal Code",
    country: "Country",
    paymentInformation: "Payment Information",
    cardNumber: "Card Number",
    expirationDate: "Expiration Date",
    cvv: "CVV",
    placeOrder: "Place Order",
    // TrustPage
    trustTitle: "Our Trust and Security",
    trustIntro: "At Paradox Protocol, your security and trust are our top priority. We are committed to providing a safe and transparent environment for all our users.",
    dataSecurityTitle: "Data Security",
    dataSecurityText: "We use advanced encryption technologies to protect your personal and financial data. All transactions are processed through secure payment gateways.",
    privacyPolicyTitle: "Privacy Policy",
    privacyPolicyText: "Your privacy is important to us. Our Privacy Policy details how we collect, use, and protect your information. We do not share your data with third parties without your consent.",
    fairPlayTitle: "Fair Play and Transparency",
    fairPlayText: "We guarantee fair play in all our challenges. Our algorithms are regularly audited to ensure the integrity and randomness of results. Transparency is a fundamental pillar of our operation.",
    customerSupportTitle: "Customer Support",
    customerSupportText: "Our customer support team is available 24/7 to answer any questions or concerns you may have. Your satisfaction is our priority.",
    validationProcessTitle: "Validation Process",
    validationProcessText: "All challenges and results undergo a rigorous validation process to ensure their accuracy and fairness. Our team of experts verifies each step to ensure the integrity of the experience.",
    // AboutPage
    aboutTitle: "About Us",
    aboutIntro: "Paradox Protocol is a team passionate about creating immersive and challenging enigma experiences. We believe the human mind is capable of unraveling the most complex mysteries.",
    ourMissionTitle: "Our Mission",
    ourMissionText: "Our mission is to provide unique challenges that stimulate critical thinking, creativity, and problem-solving. We want every user to feel like a true detective.",
    ourVisionTitle: "Our Vision",
    ourVisionText: "To be the leading platform for interactive enigma experiences, recognized for innovation, security, and the community of enthusiasts we build.",
    ourTeamTitle: "Our Team",
    ourTeamText: "We are a multidisciplinary team of game designers, developers, writers, and security experts, all united by a passion for enigmas and mysteries.",
    // ContactPage
    contactTitle: "Contact Us",
    contactIntro: "Do you have any questions, suggestions, or need support? We are here to help. Fill out the form below or use our direct contacts.",
    name: "Name",
    email: "Email",
    message: "Message",
    send: "Send",
    // HomePage
    heroTitle: "Unravel the Mystery of the Paradox Protocol",
    heroSubtitle: "An immersive enigma experience that challenges your mind.",
    learnMore: "Learn More",
    featuredChallenges: "Featured Challenges",
    challenge1Title: "The Enigma of the Forgotten Crypt",
    challenge1Desc: "Explore an ancient crypt and uncover the secrets of a lost civilization.",
    challenge2Title: "The Ghost Hacker's Code",
    challenge2Desc: "Enter the world of cybersecurity and decipher the code of a legendary hacker.",
    challenge3Title: "The Labyrinth of Dreams",
    challenge3Desc: "Navigate a surreal labyrinth where reality and illusion intertwine.",
    viewAllChallenges: "View All Challenges",
    howItWorks: "How It Works",
    step1Title: "Choose your Challenge",
    step1Desc: "Select from a variety of enigmas and mysteries, each with its own story and difficulty.",
    step2Title: "Solve the Enigmas",
    step2Desc: "Use your logic, creativity, and knowledge to unravel clues and solve puzzles.",
    step3Title: "Unravel the Mystery",
    step3Desc: "Complete the challenge and discover the truth behind the Paradox Protocol.",
    testimonials: "Testimonials",
    testimonial1: "'An incredible experience! The enigmas are challenging and the story is captivating.' - Ana P.",
    testimonial2: "'Loved every minute! Can't wait for the next challenge.' - João S.",
    testimonial3: "'The Paradox Protocol has taken enigma games to a new level.' - Sofia M.",
    faq: "Frequently Asked Questions",
    faq1Question: "What is the Paradox Protocol?",
    faq1Answer: "The Paradox Protocol is a platform for interactive enigma experiences that challenge your mind with mysteries and puzzles.",
    faq2Question: "How can I participate?",
    faq2Answer: "You can participate by choosing a challenge, creating an account, and following the instructions to solve the enigmas.",
    faq3Question: "Are the challenges for all ages?",
    faq3Answer: "Our challenges are designed for an adult audience, but some may be suitable for teenagers with supervision.",
    faq4Question: "Can I play as a team?",
    faq4Answer: "Yes, many of our challenges can be played individually or as a team, providing a collaborative experience.",
    faq5Question: "How can I contact customer support?",
    faq5Answer: "You can contact our customer support through the form on the Contact page or by email.",
    footerText: "© 2025 Paradox Protocol. All rights reserved.",
  },
  es: {
    // Common
    home: "Inicio",
    about: "Acerca de",
    trust: "Confianza",
    terms: "Términos",
    checkout: "Pagar",
    contact: "Contacto",
    language: "Idioma",
    portuguese: "Portugués",
    english: "Inglés",
    spanish: "Español",
    german: "Alemán",
    french: "Francés",
    ctaTitle: "Desafía tu mente. Desvela el misterio.",
    ctaText: "Prepárate para una experiencia inmersiva que te llevará al límite de tu percepción. El Protocolo Paradox te espera.",
    startChallenge: "Iniciar Desafío",
    // TermsPage
    termsTitle: "Términos y Condiciones",
    termsIntro: "Bienvenido a Paradox Protocol. Al acceder y utilizar nuestros servicios, acepta cumplir con los siguientes términos y condiciones. Por favor, léalos atentamente.",
    acceptanceTitle: "1. Aceptación de los Términos",
    acceptanceText: "Al utilizar Paradox Protocol, el usuario acepta estos Términos y Condiciones, así como nuestra Política de Privacidad. Si no está de acuerdo con alguna parte de estos términos, no debe utilizar nuestros servicios.",
    servicesTitle: "2. Descripción de los Servicios",
    servicesText: "Paradox Protocol ofrece una plataforma de desafíos de enigma y experiencias interactivas. Nuestros servicios pueden incluir acceso a juegos, eventos y contenidos digitales.",
    userAccountTitle: "3. Cuentas de Usuario",
    userAccountText: "Para acceder a ciertas funcionalidades, puede ser necesario crear una cuenta. El usuario es responsable de mantener la confidencialidad de su información de cuenta y de todas las actividades que ocurran bajo su cuenta.",
    paymentsTitle: "4. Pagos y Reembolsos",
    paymentsText: "Todos los pagos se procesan de forma segura. Las políticas de reembolso varían según el tipo de servicio o producto adquirido y se indicarán claramente en el momento de la compra.",
    intellectualPropertyTitle: "5. Propiedad Intelectual",
    intellectualPropertyText: "Todo el contenido y los materiales disponibles en Paradox Protocol, incluidos textos, gráficos, logotipos, imágenes y software, son propiedad de Paradox Protocol o de sus licenciantes y están protegidos por leyes de propiedad intelectual.",
    prohibitedConductTitle: "6. Conducta Prohibida",
    prohibitedConductText: "Está prohibido utilizar nuestros servicios para cualquier fin ilegal o no autorizado. Esto incluye, entre otros, la violación de derechos de propiedad intelectual, el envío de spam o la distribución de malware.",
    disclaimerTitle: "7. Exención de Garantías",
    disclaimerText: "Nuestros servicios se proporcionan 'tal cual', sin garantías de ningún tipo, expresas o implícitas. No garantizamos que los servicios serán ininterrumpidos, libres de errores o seguros.",
    limitationOfLiabilityTitle: "8. Limitación de Responsabilidad",
    limitationOfLiabilityText: "En ningún caso Paradox Protocol será responsable de daños directos, indirectos, incidentales, especiales o consecuentes que resulten del uso o la incapacidad de usar nuestros servicios.",
    lawTitle: "9. Ley Aplicable y Jurisdicción",
    lawText: "Estos Términos y Condiciones se regirán e interpretarán de acuerdo con las leyes de Portugal. Cualquier disputa se someterá a la jurisdicción exclusiva de los tribunales de Lisboa.",
    prizeTitle: "10. Condiciones de Adjudicación del Premio",
    prizeText: "El valor total del premio monetario de una temporada o desafío podrá estar condicionado a la venta de un número mínimo de entradas. Si no se alcanza este mínimo, Paradox Protocol se reserva el derecho de ajustar el valor del premio proporcionalmente o cancelar el desafío.",
    // CheckoutPage
    checkoutTitle: "Finalizar Compra",
    yourOrder: "Tu Pedido",
    product: "Producto",
    quantity: "Cantidad",
    price: "Precio",
    total: "Total",
    shippingInformation: "Información de Envío",
    fullName: "Nombre Completo",
    address: "Dirección",
    city: "Ciudad",
    postalCode: "Código Postal",
    country: "País",
    paymentInformation: "Información de Pago",
    cardNumber: "Número de Tarjeta",
    expirationDate: "Fecha de Caducidad",
    cvv: "CVV",
    placeOrder: "Realizar Pedido",
    // TrustPage
    trustTitle: "Nuestra Confianza y Seguridad",
    trustIntro: "En Paradox Protocol, tu seguridad y confianza son nuestra máxima prioridad. Nos comprometemos a proporcionar un entorno seguro y transparente para todos nuestros usuarios.",
    dataSecurityTitle: "Seguridad de los Datos",
    dataSecurityText: "Utilizamos tecnologías de cifrado avanzadas para proteger tus datos personales y financieros. Todas las transacciones se procesan a través de pasarelas de pago seguras.",
    privacyPolicyTitle: "Política de Privacidad",
    privacyPolicyText: "Tu privacidad es importante para nosotros. Nuestra Política de Privacidad detalla cómo recopilamos, usamos y protegemos tu información. No compartimos tus datos con terceros sin tu consentimiento.",
    fairPlayTitle: "Juego Justo y Transparencia",
    fairPlayText: "Garantizamos un juego justo en todos nuestros desafíos. Nuestros algoritmos se auditan regularmente para asegurar la integridad y la aleatoriedad de los resultados. La transparencia es un pilar fundamental de nuestra operación.",
    customerSupportTitle: "Atención al Cliente",
    customerSupportText: "Nuestro equipo de atención al cliente está disponible 24/7 para responder a cualquier pregunta o inquietud que puedas tener. Tu satisfacción es nuestra prioridad.",
    validationProcessTitle: "Proceso de Validación",
    validationProcessText: "Todos los desafíos y resultados se someten a un riguroso proceso de validación para garantizar su precisión y equidad. Nuestro equipo de expertos verifica cada paso para asegurar la integridad de la experiencia.",
    // AboutPage
    aboutTitle: "Acerca de Nosotros",
    aboutIntro: "Paradox Protocol es un equipo apasionado por crear experiencias de enigma inmersivas y desafiantes. Creemos que la mente humana es capaz de desentrañar los misterios más complejos.",
    ourMissionTitle: "Nuestra Misión",
    ourMissionText: "Nuestra misión es proporcionar desafíos únicos que estimulen el pensamiento crítico, la creatividad y la resolución de problemas. Queremos que cada usuario se sienta un verdadero detective.",
    ourVisionTitle: "Nuestra Visión",
    ourVisionText: "Ser la plataforma líder en experiencias de enigma interactivas, reconocida por la innovación, la seguridad y la comunidad de entusiastas que construimos.",
    ourTeamTitle: "Nuestro Equipo",
    ourTeamText: "Somos un equipo multidisciplinar de diseñadores de juegos, programadores, escritores y expertos en seguridad, todos unidos por la pasión por los enigmas y misterios.",
    // ContactPage
    contactTitle: "Contáctanos",
    contactIntro: "¿Tienes alguna pregunta, sugerencia o necesitas ayuda? Estamos aquí para ayudarte. Rellena el formulario a continuación o utiliza nuestros contactos directos.",
    name: "Nombre",
    email: "Correo Electrónico",
    message: "Mensaje",
    send: "Enviar",
    // HomePage
    heroTitle: "Desvela el Misterio del Protocolo Paradox",
    heroSubtitle: "Una experiencia de enigma inmersiva que desafía tu mente.",
    learnMore: "Saber Más",
    featuredChallenges: "Desafíos Destacados",
    challenge1Title: "El Enigma de la Cripta Olvidada",
    challenge1Desc: "Explora una cripta antigua y desvela los secretos de una civilización perdida.",
    challenge2Title: "El Código del Hacker Fantasma",
    challenge2Desc: "Entra en el mundo de la ciberseguridad y descifra el código de un hacker legendario.",
    challenge3Title: "El Laberinto de los Sueños",
    challenge3Desc: "Navega por un laberinto surrealista donde la realidad y la ilusión se entrelazan.",
    viewAllChallenges: "Ver Todos los Desafíos",
    howItWorks: "Cómo Funciona",
    step1Title: "Elige tu Desafío",
    step1Desc: "Selecciona entre una variedad de enigmas y misterios, cada uno con su propia historia y dificultad.",
    step2Title: "Resuelve los Enigmas",
    step2Desc: "Utiliza tu lógica, creatividad y conocimientos para desentrañar pistas y resolver rompecabezas.",
    step3Title: "Desvela el Misterio",
    step3Desc: "Completa el desafío y descubre la verdad detrás del Protocolo Paradox.",
    testimonials: "Testimonios",
    testimonial1: "'¡Una experiencia increíble! Los enigmas son desafiantes y la historia es cautivadora.' - Ana P.",
    testimonial2: "'¡Me encantó cada minuto! No puedo esperar al próximo desafío.' - João S.",
    testimonial3: "'El Protocolo Paradox ha llevado los juegos de enigma a un nuevo nivel.' - Sofía M.",
    faq: "Preguntas Frecuentes",
    faq1Question: "¿Qué es el Protocolo Paradox?",
    faq1Answer: "El Protocolo Paradox es una plataforma de experiencias de enigma interactivas que desafían tu mente con misterios y rompecabezas.",
    faq2Question: "¿Cómo puedo participar?",
    faq2Answer: "Puedes participar eligiendo un desafío, creando una cuenta y siguiendo las instrucciones para resolver los enigmas.",
    faq3Question: "¿Los desafíos son para todas las edades?",
    faq3Answer: "Nuestros desafíos están diseñados para un público adulto, pero algunos pueden ser adecuados para adolescentes con supervisión.",
    faq4Question: "¿Puedo jugar en equipo?",
    faq4Answer: "Sí, muchos de nuestros desafíos se pueden jugar individualmente o en equipo, proporcionando una experiencia colaborativa.",
    faq5Question: "¿Cómo puedo contactar con el servicio de atención al cliente?",
    faq5Answer: "Puedes contactar con nuestro servicio de atención al cliente a través del formulario en la página de Contacto o por correo electrónico.",
    footerText: "© 2025 Protocolo Paradox. Todos los derechos reservados.",
  },
  de: {
    // Common
    home: "Startseite",
    about: "Über uns",
    trust: "Vertrauen",
    terms: "Bedingungen",
    checkout: "Kasse",
    contact: "Kontakt",
    language: "Sprache",
    portuguese: "Portugiesisch",
    english: "Englisch",
    spanish: "Spanisch",
    german: "Deutsch",
    french: "Französisch",
    ctaTitle: "Fordere deinen Verstand heraus. Enträtsle das Geheimnis.",
    ctaText: "Bereite dich auf ein immersives Erlebnis vor, das die Grenzen deiner Wahrnehmung sprengen wird. Das Paradox Protokoll erwartet dich.",
    startChallenge: "Herausforderung starten",
    // TermsPage
    termsTitle: "Allgemeine Geschäftsbedingungen",
    termsIntro: "Willkommen beim Paradox Protokoll. Durch den Zugriff auf und die Nutzung unserer Dienste erklären Sie sich mit den folgenden Geschäftsbedingungen einverstanden. Bitte lesen Sie diese sorgfältig durch.",
    acceptanceTitle: "1. Annahme der Bedingungen",
    acceptanceText: "Durch die Nutzung des Paradox Protokolls erklären Sie sich mit diesen Allgemeinen Geschäftsbedingungen sowie unserer Datenschutzrichtlinie einverstanden. Wenn Sie mit einem Teil dieser Bedingungen nicht einverstanden sind, sollten Sie unsere Dienste nicht nutzen.",
    servicesTitle: "2. Beschreibung der Dienste",
    servicesText: "Das Paradox Protokoll bietet eine Plattform für Rätselherausforderungen und interaktive Erlebnisse. Unsere Dienste können den Zugang zu Spielen, Veranstaltungen und digitalen Inhalten umfassen.",
    userAccountTitle: "3. Benutzerkonten",
    userAccountText: "Um auf bestimmte Funktionen zugreifen zu können, müssen Sie möglicherweise ein Konto erstellen. Sie sind dafür verantwortlich, die Vertraulichkeit Ihrer Kontoinformationen und aller Aktivitäten, die unter Ihrem Konto stattfinden, zu wahren.",
    paymentsTitle: "4. Zahlungen und Rückerstattungen",
    paymentsText: "Alle Zahlungen werden sicher verarbeitet. Die Rückerstattungsrichtlinien variieren je nach Art des gekauften Dienstes oder Produkts und werden zum Zeitpunkt des Kaufs klar angegeben.",
    intellectualPropertyTitle: "5. Geistiges Eigentum",
    intellectualPropertyText: "Alle Inhalte und Materialien, die auf dem Paradox Protokoll verfügbar sind, einschließlich Texte, Grafiken, Logos, Bilder und Software, sind Eigentum des Paradox Protokolls oder seiner Lizenzgeber und durch Gesetze zum geistigen Eigentum geschützt.",
    prohibitedConductTitle: "6. Verbotenes Verhalten",
    prohibitedConductText: "Es ist verboten, unsere Dienste für illegale oder nicht autorisierte Zwecke zu nutzen. Dies umfasst, ist aber nicht beschränkt auf, die Verletzung von Rechten an geistigem Eigentum, das Versenden von Spam oder die Verbreitung von Malware.",
    disclaimerTitle: "7. Haftungsausschluss",
    disclaimerText: "Unsere Dienste werden 'wie besehen' und ohne jegliche ausdrückliche oder stillschweigende Gewährleistung bereitgestellt. Wir garantieren nicht, dass die Dienste ununterbrochen, fehlerfrei oder sicher sind.",
    limitationOfLiabilityTitle: "8. Haftungsbeschränkung",
    limitationOfLiabilityText: "In keinem Fall haftet das Paradox Protokoll für direkte, indirekte, zufällige, besondere oder Folgeschäden, die sich aus der Nutzung oder der Unfähigkeit zur Nutzung unserer Dienste ergeben.",
    lawTitle: "9. Anwendbares Recht und Gerichtsstand",
    lawText: "Diese Allgemeinen Geschäftsbedingungen unterliegen den Gesetzen Portugals und werden entsprechend ausgelegt. Alle Streitigkeiten werden der ausschließlichen Zuständigkeit der Gerichte von Lissabon unterbreitet.",
    prizeTitle: "10. Bedingungen für die Preisvergabe",
    prizeText: "Der Gesamtwert des Geldpreises einer Saison oder Herausforderung kann an den Verkauf einer Mindestanzahl von Tickets gebunden sein. Wird dieses Minimum nicht erreicht, behält sich das Paradox Protokoll das Recht vor, den Preiswert proportional anzupassen oder die Herausforderung abzubrechen.",
    // CheckoutPage
    checkoutTitle: "Kasse",
    yourOrder: "Ihre Bestellung",
    product: "Produkt",
    quantity: "Menge",
    price: "Preis",
    total: "Gesamt",
    shippingInformation: "Versandinformationen",
    fullName: "Vollständiger Name",
    address: "Adresse",
    city: "Stadt",
    postalCode: "Postleitzahl",
    country: "Land",
    paymentInformation: "Zahlungsinformationen",
    cardNumber: "Kartennummer",
    expirationDate: "Ablaufdatum",
    cvv: "CVV",
    placeOrder: "Bestellung aufgeben",
    // TrustPage
    trustTitle: "Unser Vertrauen und unsere Sicherheit",
    trustIntro: "Beim Paradox Protokoll haben Ihre Sicherheit und Ihr Vertrauen oberste Priorität. Wir sind bestrebt, allen unseren Nutzern eine sichere und transparente Umgebung zu bieten.",
    dataSecurityTitle: "Datensicherheit",
    dataSecurityText: "Wir verwenden fortschrittliche Verschlüsselungstechnologien, um Ihre persönlichen und finanziellen Daten zu schützen. Alle Transaktionen werden über sichere Zahlungsgateways abgewickelt.",
    privacyPolicyTitle: "Datenschutzrichtlinie",
    privacyPolicyText: "Ihre Privatsphäre ist uns wichtig. Unsere Datenschutzrichtlinie beschreibt, wie wir Ihre Informationen sammeln, verwenden und schützen. Wir geben Ihre Daten ohne Ihre Zustimmung nicht an Dritte weiter.",
    fairPlayTitle: "Faires Spiel und Transparenz",
    fairPlayText: "Wir garantieren faires Spiel bei all unseren Herausforderungen. Unsere Algorithmen werden regelmäßig überprüft, um die Integrität und Zufälligkeit der Ergebnisse zu gewährleisten. Transparenz ist ein grundlegender Pfeiler unseres Betriebs.",
    customerSupportTitle: "Kundensupport",
    customerSupportText: "Unser Kundensupport-Team steht Ihnen rund um die Uhr zur Verfügung, um alle Fragen oder Bedenken zu beantworten. Ihre Zufriedenheit ist unsere Priorität.",
    validationProcessTitle: "Validierungsprozess",
    validationProcessText: "Alle Herausforderungen und Ergebnisse durchlaufen einen strengen Validierungsprozess, um ihre Genauigkeit und Fairness zu gewährleisten. Unser Expertenteam überprüft jeden Schritt, um die Integrität des Erlebnisses sicherzustellen.",
    // AboutPage
    aboutTitle: "Über uns",
    aboutIntro: "Das Paradox Protokoll ist ein Team, das sich leidenschaftlich der Schaffung immersiver und herausfordernder Rätselerlebnisse widmet. Wir glauben, dass der menschliche Verstand in der Lage ist, die komplexesten Geheimnisse zu entschlüsseln.",
    ourMissionTitle: "Unsere Mission",
    ourMissionText: "Unsere Mission ist es, einzigartige Herausforderungen zu bieten, die kritisches Denken, Kreativität und Problemlösung anregen. Wir möchten, dass sich jeder Benutzer wie ein echter Detektiv fühlt.",
    ourVisionTitle: "Unsere Vision",
    ourVisionText: "Die führende Plattform für interaktive Rätselerlebnisse zu sein, anerkannt für Innovation, Sicherheit und die Gemeinschaft von Enthusiasten, die wir aufbauen.",
    ourTeamTitle: "Unser Team",
    ourTeamText: "Wir sind ein multidisziplinäres Team aus Spieldesignern, Programmierern, Autoren und Sicherheitsexperten, die alle durch die Leidenschaft für Rätsel und Geheimnisse vereint sind.",
    // ContactPage
    contactTitle: "Kontakt",
    contactIntro: "Haben Sie Fragen, Anregungen oder benötigen Sie Unterstützung? Wir sind für Sie da. Füllen Sie das untenstehende Formular aus oder nutzen Sie unsere direkten Kontakte.",
    name: "Name",
    email: "E-Mail",
    message: "Nachricht",
    send: "Senden",
    // HomePage
    heroTitle: "Enträtsle das Geheimnis des Paradox Protokolls",
    heroSubtitle: "Ein immersives Rätselerlebnis, das deinen Verstand herausfordert.",
    learnMore: "Mehr erfahren",
    featuredChallenges: "Besondere Herausforderungen",
    challenge1Title: "Das Rätsel der vergessenen Krypta",
    challenge1Desc: "Erkunde eine alte Krypta und lüfte die Geheimnisse einer verlorenen Zivilisation.",
    challenge2Title: "Der Code des Geisterhackers",
    challenge2Desc: "Tauche ein in die Welt der Cybersicherheit und entschlüssle den Code eines legendären Hackers.",
    challenge3Title: "Das Labyrinth der Träume",
    challenge3Desc: "Navigiere durch ein surreales Labyrinth, in dem Realität und Illusion verschmelzen.",
    viewAllChallenges: "Alle Herausforderungen anzeigen",
    howItWorks: "So funktioniert's",
    step1Title: "Wähle deine Herausforderung",
    step1Desc: "Wähle aus einer Vielzahl von Rätseln und Geheimnissen, jedes mit seiner eigenen Geschichte und Schwierigkeit.",
    step2Title: "Löse die Rätsel",
    step2Desc: "Nutze deine Logik, Kreativität und dein Wissen, um Hinweise zu entschlüsseln und Rätsel zu lösen.",
    step3Title: "Enträtsle das Geheimnis",
    step3Desc: "Schließe die Herausforderung ab und entdecke die Wahrheit hinter dem Paradox Protokoll.",
    testimonials: "Referenzen",
    testimonial1: "'Ein unglaubliches Erlebnis! Die Rätsel sind herausfordernd und die Geschichte ist fesselnd.' - Ana P.",
    testimonial2: "'Ich habe jede Minute genossen! Ich kann die nächste Herausforderung kaum erwarten.' - João S.",
    testimonial3: "'Das Paradox Protokoll hat Rätselspiele auf ein neues Niveau gehoben.' - Sofia M.",
    faq: "Häufig gestellte Fragen",
    faq1Question: "Was ist das Paradox Protokoll?",
    faq1Answer: "Das Paradox Protokoll ist eine Plattform für interaktive Rätselerlebnisse, die deinen Verstand mit Geheimnissen und Rätseln herausfordern.",
    faq2Question: "Wie kann ich teilnehmen?",
    faq2Answer: "Du kannst teilnehmen, indem du eine Herausforderung wählst, ein Konto erstellst und den Anweisungen zum Lösen der Rätsel folgst.",
    faq3Question: "Sind die Herausforderungen für alle Altersgruppen geeignet?",
    faq3Answer: "Unsere Herausforderungen sind für ein erwachsenes Publikum konzipiert, aber einige können unter Aufsicht auch für Jugendliche geeignet sein.",
    faq4Question: "Kann ich im Team spielen?",
    faq4Answer: "Ja, viele unserer Herausforderungen können einzeln oder im Team gespielt werden, was ein kollaboratives Erlebnis bietet.",
    faq5Question: "Wie kann ich den Kundensupport kontaktieren?",
    faq5Answer: "Sie können unseren Kundensupport über das Formular auf der Kontaktseite oder per E-Mail kontaktieren.",
    footerText: "© 2025 Paradox Protokoll. Alle Rechte vorbehalten.",
  },
  fr: {
    // Common
    home: "Accueil",
    about: "À propos",
    trust: "Confiance",
    terms: "Conditions",
    checkout: "Paiement",
    contact: "Contact",
    language: "Langue",
    portuguese: "Portugais",
    english: "Anglais",
    spanish: "Espagnol",
    german: "Allemand",
    french: "Français",
    ctaTitle: "Défiez votre esprit. Démêlez le mystère.",
    ctaText: "Préparez-vous à une expérience immersive qui repoussera les limites de votre perception. Le Protocole Paradox vous attend.",
    startChallenge: "Commencer le défi",
    // TermsPage
    termsTitle: "Conditions Générales",
    termsIntro: "Bienvenue sur Paradox Protocol. En accédant et en utilisant nos services, vous acceptez de vous conformer aux conditions générales suivantes. Veuillez les lire attentivement.",
    acceptanceTitle: "1. Acceptation des Conditions",
    acceptanceText: "En utilisant Paradox Protocol, vous acceptez ces Conditions Générales, ainsi que notre Politique de Confidentialité. Si vous n'êtes pas d'accord avec une partie de ces conditions, vous ne devez pas utiliser nos services.",
    servicesTitle: "2. Description des Services",
    servicesText: "Paradox Protocol offre une plateforme de défis d'énigmes et d'expériences interactives. Nos services peuvent inclure l'accès à des jeux, des événements et du contenu numérique.",
    userAccountTitle: "3. Comptes Utilisateur",
    userAccountText: "Pour accéder à certaines fonctionnalités, il peut être nécessaire de créer un compte. Vous êtes responsable du maintien de la confidentialité des informations de votre compte et de toutes les activités qui se produisent sous votre compte.",
    paymentsTitle: "4. Paiements et Remboursements",
    paymentsText: "Tous les paiements sont traités en toute sécurité. Les politiques de remboursement varient en fonction du type de service ou de produit acheté et seront clairement indiquées au moment de l'achat.",
    intellectualPropertyTitle: "5. Propriété Intellectuelle",
    intellectualPropertyText: "Tout le contenu et les matériaux disponibles sur Paradox Protocol, y compris les textes, graphiques, logos, images et logiciels, sont la propriété de Paradox Protocol ou de ses concédants de licence et sont protégés par les lois sur la propriété intellectuelle.",
    prohibitedConductTitle: "6. Conduite Interdite",
    prohibitedConductText: "Il est interdit d'utiliser nos services à des fins illégales ou non autorisées. Cela inclut, sans s'y limiter, la violation des droits de propriété intellectuelle, l'envoi de spam ou la distribution de logiciels malveillants.",
    disclaimerTitle: "7. Exclusion de Garanties",
    disclaimerText: "Nos services sont fournis 'tels quels', sans garantie d'aucune sorte, expresse ou implicite. Nous ne garantissons pas que les services seront ininterrompus, sans erreur ou sécurisés.",
    limitationOfLiabilityTitle: "8. Limitation de Responsabilité",
    limitationOfLiabilityText: "En aucun cas Paradox Protocol ne sera responsable des dommages directs, indirects, accessoires, spéciaux ou consécutifs résultant de l'utilisation ou de l'incapacité d'utiliser nos services.",
    lawTitle: "9. Loi Applicable et Juridiction",
    lawText: "Les présentes Conditions Générales seront régies et interprétées conformément aux lois du Portugal. Tout litige sera soumis à la juridiction exclusive des tribunaux de Lisbonne.",
    prizeTitle: "10. Conditions d'Attribution du Prix",
    prizeText: "La valeur totale du prix monétaire d'une saison ou d'un défi peut être conditionnée par la vente d'un nombre minimum de billets. Si ce minimum n'est pas atteint, Paradox Protocol se réserve le droit d'ajuster la valeur du prix proportionnellement ou d'annuler le défi.",
    // CheckoutPage
    checkoutTitle: "Paiement",
    yourOrder: "Votre Commande",
    product: "Produit",
    quantity: "Quantité",
    price: "Prix",
    total: "Total",
    shippingInformation: "Informations de Livraison",
    fullName: "Nom Complet",
    address: "Adresse",
    city: "Ville",
    postalCode: "Code Postal",
    country: "Pays",
    paymentInformation: "Informations de Paiement",
    cardNumber: "Numéro de Carte",
    expirationDate: "Date d'Expiration",
    cvv: "CVV",
    placeOrder: "Passer la Commande",
    // TrustPage
    trustTitle: "Notre Confiance et Sécurité",
    trustIntro: "Chez Paradox Protocol, votre sécurité et votre confiance sont notre priorité absolue. Nous nous engageons à fournir un environnement sûr et transparent à tous nos utilisateurs.",
    dataSecurityTitle: "Sécurité des Données",
    dataSecurityText: "Nous utilisons des technologies de cryptage avancées pour protéger vos données personnelles et financières. Toutes les transactions sont traitées via des passerelles de paiement sécurisées.",
    privacyPolicyTitle: "Politique de Confidentialité",
    privacyPolicyText: "Votre vie privée est importante pour nous. Notre Politique de Confidentialité détaille comment nous collectons, utilisons et protégeons vos informations. Nous ne partageons pas vos données avec des tiers sans votre consentement.",
    fairPlayTitle: "Jeu Équitable et Transparence",
    fairPlayText: "Nous garantissons un jeu équitable dans tous nos défis. Nos algorithmes sont régulièrement audités pour assurer l'intégrité et le caractère aléatoire des résultats. La transparence est un pilier fondamental de notre fonctionnement.",
    customerSupportTitle: "Support Client",
    customerSupportText: "Notre équipe de support client est disponible 24h/24 et 7j/7 pour répondre à toutes vos questions ou préoccupations. Votre satisfaction est notre priorité.",
    validationProcessTitle: "Processus de Validation",
    validationProcessText: "Tous les défis et résultats sont soumis à un processus de validation rigoureux pour garantir leur exactitude et leur équité. Notre équipe d'experts vérifie chaque étape pour assurer l'intégrité de l'expérience.",
    // AboutPage
    aboutTitle: "À Propos de Nous",
    aboutIntro: "Paradox Protocol est une équipe passionnée par la création d'expériences d'énigmes immersives et stimulantes. Nous croyons que l'esprit humain est capable de démêler les mystères les plus complexes.",
    ourMissionTitle: "Notre Mission",
    ourMissionText: "Notre mission est de proposer des défis uniques qui stimulent la pensée critique, la créativité et la résolution de problèmes. Nous voulons que chaque utilisateur se sente comme un véritable détective.",
    ourVisionTitle: "Notre Vision",
    ourVisionText: "Être la plateforme leader en expériences d'énigmes interactives, reconnue pour l'innovation, la sécurité et la communauté d'enthousiastes que nous construisons.",
    ourTeamTitle: "Notre Équipe",
    ourTeamText: "Nous sommes une équipe multidisciplinaire de concepteurs de jeux, de développeurs, d'écrivains et d'experts en sécurité, tous unis par la passion des énigmes et des mystères.",
    // ContactPage
    contactTitle: "Contactez-nous",
    contactIntro: "Vous avez des questions, des suggestions ou besoin d'aide ? Nous sommes là pour vous aider. Remplissez le formulaire ci-dessous ou utilisez nos contacts directs.",
    name: "Nom",
    email: "E-mail",
    message: "Message",
    send: "Envoyer",
    // HomePage
    heroTitle: "Démêlez le Mystère du Protocole Paradox",
    heroSubtitle: "Une expérience d'énigme immersive qui défie votre esprit.",
    learnMore: "En savoir plus",
    featuredChallenges: "Défis en Vedette",
    challenge1Title: "L'Énigme de la Crypte Oubliée",
    challenge1Desc: "Explorez une crypte ancienne et découvrez les secrets d'une civilisation perdue.",
    challenge2Title: "Le Code du Hacker Fantôme",
    challenge2Desc: "Entrez dans le monde de la cybersécurité et déchiffrez le code d'un hacker légendaire.",
    challenge3Title: "Le Labyrinthe des Rêves",
    challenge3Desc: "Naviguez dans un labyrinthe surréaliste où la réalité et l'illusion s'entremêlent.",
    viewAllChallenges: "Voir tous les défis",
    howItWorks: "Comment ça marche",
    step1Title: "Choisissez votre défi",
    step1Desc: "Sélectionnez parmi une variété d'énigmes et de mystères, chacun avec sa propre histoire et difficulté.",
    step2Title: "Résolvez les énigmes",
    step2Desc: "Utilisez votre logique, votre créativité et vos connaissances pour démêler les indices et résoudre les énigmes.",
    step3Title: "Démêlez le mystère",
    step3Desc: "Terminez le défi et découvrez la vérité derrière le Protocole Paradox.",
    testimonials: "Témoignages",
    testimonial1: "'Une expérience incroyable ! Les énigmes sont stimulantes et l'histoire est captivante.' - Ana P.",
    testimonial2: "'J'ai adoré chaque minute ! J'ai hâte du prochain défi.' - João S.",
    testimonial3: "'Le Protocole Paradox a élevé les jeux d'énigmes à un nouveau niveau.' - Sofia M.",
    faq: "Questions Fréquentes",
    faq1Question: "Qu'est-ce que le Protocole Paradox ?",
    faq1Answer: "Le Protocole Paradox est une plateforme d'expériences d'énigmes interactives qui défient votre esprit avec des mystères et des énigmes.",
    faq2Question: "Comment puis-je participer ?",
    faq2Answer: "Vous pouvez participer en choisissant un défi, en créant un compte et en suivant les instructions pour résoudre les énigmes.",
    faq3Question: "Les défis sont-ils pour tous les âges ?",
    faq3Answer: "Nos défis sont conçus pour un public adulte, mais certains peuvent convenir aux adolescents sous surveillance.",
    faq4Question: "Puis-je jouer en équipe ?",
    faq4Answer: "Oui, de nombreux défis peuvent être joués individuellement ou en équipe, offrant une expérience collaborative.",
    faq5Question: "Comment puis-je contacter le support client ?",
    faq5Answer: "Vous pouvez contacter notre support client via le formulaire sur la page Contact ou par e-mail.",
    footerText: "© 2025 Protocole Paradox. Tous droits réservés.",
  },
  // Add more languages as needed
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'pt'; // Default to Portuguese
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key; // Fallback to key if translation not found
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);


